# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-REPL-Plugin-NAS
version:      0.0501
version_from: lib/Devel/REPL/Plugin/NAS.pm
installdirs:  site
requires:
    Devel::REPL:              0
    Net::ApplianceL::Session: 1.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
